[build]
command = "mv server.netlify.ts server.ts && mv app/root.netlify.tsx app/root.tsx && npm run build"
publish = "dist/client"

[dev]
# Run "npm run dev" to start the dev server
# Enable the static server for edge functions, because Remix handles the dev server
framework = "#static"

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/build/*"

[headers.values]

"Cache-Control" = "public, max-age=31560000, immutable"

# These are only used to set up the template, and are not used in the build
# If you want to update the real values, change them in the site UI or CLI
[template.environment]
PUBLIC_STORE_DOMAIN = "mock.shop"
SESSION_SECRET = "foobar"
